no_english = int(raw_input())
a = raw_input()
no_french = int(raw_input())
b= raw_input()
rollno_english = a.split()
rollno_french = b.split()
list_rollno_english = list(map(int, rollno_english))
list_rollno_french = list(map(int, rollno_french))
set_rollno_english= set(list_rollno_english)
set_rollno_french  = set(list_rollno_french )
both = (set_rollno_english).union(set_rollno_french)
print(len(both))
